# Netlify Configuration for UNO React App

[build]
  # Directory to build from
  base = "."
  
  # Build command
  command = "npm run build"
  
  # Directory that contains the deploy-ready HTML files and assets
  publish = "dist"

# Redirect all requests to index.html for client-side routing (SPA)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Production environment variables (optional)
[build.environment]
  NODE_VERSION = "20"

# Headers for better security and caching
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache static assets for 1 year
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache cards images
[[headers]]
  for = "/cards/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
